export const SIGIN_IN = "SIGIN_IN";
export const SET_USER = "SET_USER";
export const SET_ERROR = "SET_ERROR";
export const SET_ORGANIZATION_LIST = "SET_ORGANIZATION_LIST";
export const ORGANIZATION_LIST = "ORGANIZATION_LIST";
/***********LOGIN ACTIONS*********************/
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const GET_ORGANIZATIONS_REQUEST = "GET_ORGANIZATIONS_REQUEST";
export const GET_ORGANIZATIONS_SUCCESS = "GET_ORGANIZATIONS_SUCCESS";
export const GET_ORGANIZATIONS_FAILURE = "GET_ORGANIZATIONS_FAILURE";
export const GET_ORGANIZATION_REQUEST = "GET_ORGANIZATION_REQUEST";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";

export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_ERROR = "UPDATE_ORGANIZATION_ERROR";

export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";
export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_ERROR = "DELETE_ORGANIZATION_ERROR";

export const CREATE_ORGANIZATION = "CREATE_ORGANIZATION";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
export const CREATE_ORGANIZATION_ERROR = "CREATE_ORGANIZATION_ERROR";

export const GET_ORGANIZATIONS_COUNT_SUCCESS =
  "GET_ORGANIZATIONS_COUNT_SUCCESS";
export const GET_ORGANIZATIONS_COUNT_FAILURE =
  " GET_ORGANIZATIONS_COUNT_FAILURE";
export const GET_ORGANIZATIONS_COUNT = "GET_ORGANIZATIONS_COUNT";

/****************************USERS----CONSTANTS******************************************************/
export const FETCH_USER_LIST = "FETCH_USER_LIST";
export const FETCH_USER_LIST_SUCCESS = "FETCH_USER_LIST_SUCCESS";
export const FETCH_USER_LIST_ERROR = "FETCH_USER_LIST_ERROR";

export const FETCH_USER_BY_ID = "FETCH_USER_BY_ID";
export const FETCH_USER_BY_ID_SUCCESS = "FETCH_USER_BY_ID_SUCCESS";
export const FETCH_USER_BY_ID_ERROR = "FETCH_USER_BY_ID_ERROR";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const GET_USERS_COUNT_SUCCESS = "GET_USERS_COUNT_SUCCESS";
export const GET_USERS_COUNT_FAILURE = " GET_USERS_COUNT_FAILURE";
export const GET_USERS_COUNT = "GET_USERS_COUNT";
/************************************************************* */

export const GET_COMPLAINTS_REQUEST = "GET_COMPLAINTS_REQUEST";
export const GET_COMPLAINTS_FAILURE = "GET_COMPLAINTS_FAILURE";
export const GET_COMPLAINT_REQUEST = "GET_COMPLAINT_REQUEST";
export const GET_COMPLAINTS_SUCCESS = "GET_COMPLAINTS_SUCCESS";
export const GET_COMPLAINT_FAILURE = "GET_COMPLAINT_FAILURE";
export const GET_COMPLAINT_SUCCESS = " GET_COMPLAINT_SUCCESS";
export const UPDATE_COMPLAINT = "UPDATE_COMPLAINT";
export const UPDATE_COMPLAINT_SUCCESS = "UPDATE_COMPLAINT_SUCCESS";
export const UPDATE_COMPLAINT_ERROR = "UPDATE_COMPLAINT_ERROR";
export const DELETE_COMPLAINT = "DELETE_COMPLAINT";
export const DELETE_COMPLAINT_ERROR = "DELETE_COMPLAINT_ERROR";
export const DELETE_COMPLAINT_SUCCESS = "DELETE_COMPLAINT_SUCCES";
export const CREATE_COMPLAINT = "CREATE_COMPLAINT";
export const CREATE_COMPLAINT_SUCCESS = "CREATE_COMPLAINT_SUCCES";
export const CREATE_COMPLAINT_ERROR = "CREATE_COMPLAINT_ERROR";

export const GET_COMPLAINT_COUNT = "GET_COMPLAINT_COUNT";
export const GET_COMPLAINT_COUNT_SUCCESS = "GET_COMPLAINT_COUNT_SUCCESS";
export const GET_COMPLAINT_COUNT_FAILURE = "GET_COMPLAINT_COUNT_FAILURE";

/*************************ITEM-CONSTANTS************************* */
export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE";
export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_FAILURE = "GET_ITEM_FAILURE";

export const UPDATE_ITEM = "UPDATE_ITEM";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_ERROR = "UPDATE_ITEM_ERROR";

export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_ERROR = "DELETE_ITEM_ERROR";

export const CREATE_ITEM = "CREATE_ITEM";
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const CREATE_ITEM_ERROR = "CREATE_ITEM_ERROR";

export const GET_ITEMS_COUNT_SUCCESS = "GET_ITEMS_COUNT_SUCCESS";
export const GET_ITEMS_COUNT_FAILURE = " GET_ITEMS_COUNT_FAILURE";
export const GET_ITEMS_COUNT = "GET_ITEMS_COUNT";

/*******************************department-constants***************/
export const GET_DEPARTMENTS_REQUEST = "GET_DEPARTMENTS_REQUEST";
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
export const GET_DEPARTMENTS_FAILURE = "GET_DEPARTMENTS_FAILURE";
export const GET_DEPARTMENT_REQUEST = "GET_DEPARTMENT_REQUEST";
export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";
export const GET_DEPARTMENT_FAILURE = "GET_DEPARTMENT_FAILURE";

export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_ERROR = "UPDATE_DEPARTMENT_ERROR";

export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_ERROR = "DELETE_DEPARTMENT_ERROR";

export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const CREATE_DEPARTMENT_SUCCESS = "CREATE_DEPARTMENT_SUCCESS";
export const CREATE_DEPARTMENT_ERROR = "CREATE_DEPARTMENT_ERROR";

export const GET_DEPARTMENTS_COUNT_SUCCESS = "GET_DEPARTMENTS_COUNT_SUCCESS";
export const GET_DEPARTMENTS_COUNT_FAILURE = " GET_DEPARTMENTS_COUNT_FAILURE";
export const GET_DEPARTMENTS_COUNT = "GET_DEPARTMENTS_COUNT";

/*************************************************CATEGORIES***********************/
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";
export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";

export const GET_CATEGORIES_COUNT_SUCCESS = "GET_CATEGORIES_COUNT_SUCCESS";
export const GET_CATEGORIES_COUNT_FAILURE = " GET_CATEGORIES_COUNT_FAILURE";
export const GET_CATEGORIES_COUNT = "GET_CATEGORIES_COUNT";


/***********************************************REQUEST_CONSTATNTS***********************************/

export const GET_REQUESTS_REQUEST = "GET_REQUESTS_REQUEST";
export const GET_REQUESTS_SUCCESS = "GET_REQUESTS_SUCCESS";
export const GET_REQUESTS_FAILURE = "GET_REQUESTS_FAILURE";
export const GET_REQUEST_REQUEST = "GET_REQUEST_REQUEST";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GET_REQUEST_FAILURE = "GET_REQUEST_FAILURE";

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS";
export const UPDATE_REQUEST_ERROR = "UPDATE_REQUEST_ERROR";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_ERROR = "DELETE_REQUEST_ERROR";

export const CREATE_REQUEST = "CREATE_REQUEST";
export const CREATE_REQUEST_SUCCESS = "CREATE_REQUEST_SUCCESS";
export const CREATE_REQUEST_ERROR = "CREATE_REQUEST_ERROR";

export const GET_REQUESTS_COUNT_SUCCESS =
  "GET_REQUESTS_COUNT_SUCCESS";
export const GET_REQUESTS_COUNT_FAILURE =
  " GET_REQUESTS_COUNT_FAILURE";
export const GET_REQUESTS_COUNT = "GET_REQUESTS_COUNT";

/**********************************************************VENDOR_CONSTANTS**************************/
export const GET_VENDORS_REQUEST = "GET_VENDORS_REQUEST";
export const GET_VENDORS_SUCCESS = "GET_VENDORS_SUCCESS";
export const GET_VENDORS_FAILURE = "GET_VENDORS_FAILURE";
export const GET_VENDOR_REQUEST = "GET_VENDOR_REQUEST";
export const GET_VENDOR_SUCCESS = "GET_VENDOR_SUCCESS";
export const GET_VENDOR_FAILURE = "GET_VENDOR_FAILURE";

export const UPDATE_VENDOR = "UPDATE_VENDOR";
export const UPDATE_VENDOR_SUCCESS = "UPDATE_VENDOR_SUCCESS";
export const UPDATE_VENDOR_ERROR = "UPDATE_VENDOR_ERROR";

export const DELETE_VENDOR = "DELETE_VENDOR";
export const DELETE_VENDOR_SUCCESS = "DELETE_VENDOR_SUCCESS";
export const DELETE_VENDOR_ERROR = "DELETE_VENDOR_ERROR";

export const CREATE_VENDOR = "CREATE_VENDOR";
export const CREATE_VENDOR_SUCCESS = "CREATE_VENDOR_SUCCESS";
export const CREATE_VENDOR_ERROR = "CREATE_VENDOR_ERROR";

export const GET_VENDORS_COUNT_SUCCESS =
  "GET_VENDORS_COUNT_SUCCESS";
export const GET_VENDORS_COUNT_FAILURE =
  " GET_VENDORS_COUNT_FAILURE";
export const GET_VENDORS_COUNT = "GET_VENDORS_COUNT";